# Use an official Node.js runtime as the base image
FROM node:lts

# Set the working directory in the container
WORKDIR /

# Copy package.json and package-lock.json to the working directory
COPY . .

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Vite.js application
RUN npm run build

# Expose the port on which the app will run
EXPOSE 3001

# Define the command to run the application
CMD ["npm", "run", "dev"]